export const players = [
  {
    id: 1,
    name: "Alex Smeall (C)",
    team_id: 1,
    team_name: "Fogtown Leprechauns",
    number: 21,
    position: "D",
    games: 11,
    goals: 9,
    assists: 12
  },
  {
    id: 2,
    name: "Jason Duggan (A)",
    team_id: 1,
    team_name: "Fogtown Leprechauns",
    number: 10,
    position: "F",
    games: 9,
    goals: 13,
    assists: 4
  },
  {
    id: 3,
    name: "Grant Samson (A)",
    team_id: 1,
    team_name: "Fogtown Leprechauns",
    number: 11,
    position: "F",
    games: 8,
    goals: 15,
    assists: 8
  },
  {
    id: 4,
    name: "Josh Shears",
    team_id: 1,
    team_name: "Fogtown Leprechauns",
    number: 17,
    position: "F",
    games: 7,
    goals: 17,
    assists: 6
  },
  {
    id: 5,
    name: "Matthew Cheeks",
    team_id: 1,
    team_name: "Fogtown Leprechauns",
    number: 88,
    position: "F",
    games: 9,
    goals: 14,
    assists: 3
  },
  {
    id: 6,
    name: "Liam Henebury",
    team_id: 1,
    team_name: "Fogtown Leprechauns",
    number: 2,
    position: "D",
    games: 10,
    goals: 1,
    assists: 7
  },
  {
    id: 7,
    name: "Greg Abbott",
    team_id: 1,
    team_name: "Fogtown Leprechauns",
    number: 3,
    position: "D",
    games: 8,
    goals: 2,
    assists: 2
  },
  {
    id: 8,
    name: "Alan McDonald",
    team_id: 1,
    team_name: "Fogtown Leprechauns",
    number: 15,
    position: "F",
    games: 8,
    goals: 2,
    assists: 1
  },
  {
    id: 9,
    name: "Jamie Greeley",
    team_id: 1,
    team_name: "Fogtown Leprechauns",
    number: 96,
    position: "F",
    games: 4,
    goals: 4,
    assists: 7
  },
  {
    id: 10,
    name: "Nick Tuck",
    team_id: 1,
    team_name: "Fogtown Leprechauns",
    number: 48,
    position: "D",
    games: 4,
    goals: 2,
    assists: 3
  },
  {
    id: 11,
    name: "Christian O'Leary",
    team_id: 1,
    team_name: "Fogtown Leprechauns",
    number: 44,
    position: "F",
    games: 3,
    goals: 1,
    assists: 1
  },
  {
    id: 12,
    name: "Phillip Fowler",
    team_id: 1,
    team_name: "Fogtown Leprechauns",
    number: 35,
    position: "G",
    games: 8,
    wins: 4,
    goalsAgainst: 43
  },
  {
    id: 13,
    name: "Sean Tobin",
    team_id: 1,
    team_name: "Fogtown Leprechauns",
    number: 1,
    position: "G",
    games: 4,
    wins: 3,
    goalsAgainst: 19
  },
  {
    id: 14,
    name: "Drew Saunders",
    team_id: 2,
    team_name: "Duck Island Saints",
    number: 52,
    position: "F",
    games: 9,
    goals: 29,
    assists: 0
  },
];
